name: Run JavaScript Code

on:
  push:
    branches: [ "main" ]

jobs:
  run-js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Code (error.js)
        run: node error.js
